name: Generate Final Document

on:
  push:
    branches:
      - main

jobs:
  generate_document:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Generate Final Document
        run: |
          # Initialize the final document
          echo "Final Document:" > final_document.md

          # Find all JavaScript files enclosed in folders
          find . -type f -name "*.js" -exec bash -c '
            # Extract folder name and markdown file content
            folder="$(dirname "{}")"
            markdown_file="$folder/instructions.md"
            markdown_content=$(cat "$markdown_file")

            # Append to the final document
            echo "Folder Name:" >> final_document.md
            echo "  - $folder - $markdown_content" >> final_document.md
          ' \;

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add final_document.md
          git commit -m "Generate final document"
          git push
